default: &default
   adapter: postgresql
   encoding: unicode
   host: db
   username: postgres
   password: postgres
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   timeout: 5000

development:
  <<: *default
  database: ror_social_scaffold_development


test:
  <<: *default
  database: ror_social_scaffold_test